[package]
name = "kml_rhi"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.38.0+1.3.281", optional = true }
bitflags = "2.6.0"
thiserror = "1.0.63"

[features]
default = ["metal", "vulkan"]
metal = []
vulkan = ["ash"]